import brands from '../data/brands.json';
import categorySystems from '../data/categorySystems.json';
export {brands, categorySystems};
export function normalize(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
export function findBrand(q){const n=normalize(q);return brands.find(b=>b.id===n||normalize(b.name)===n||(b.aliases||[]).some(a=>normalize(a)===n))||null}
export function searchBrands(q){const n=normalize(q);if(!n)return brands;return brands.filter(b=>b.id.includes(n)||normalize(b.name).includes(n)||(b.aliases||[]).some(a=>normalize(a).includes(n))||b.segment.toLowerCase().includes(n)).slice(0,12)}
export function pct(v){return `${Math.round((v||0)*100)}%`}
export function categorySizeDefault(cat){const c=categorySystems[cat]||categorySystems.tops;if(cat==='jeans')return 'W32 / L32';if(cat==='lingerie')return 'EU 75 C';return (c.sizes||['M'])[3]||(c.sizes||['M'])[0]}
export function confidenceV2({fromBrand,toBrand,category='tops',material='standard'}){const f=findBrand(fromBrand)||brands[0],t=findBrand(toBrand)||brands[2];let s=(f.baseConfidence+t.baseConfidence)/2;if(f.sourceType==='public'&&t.sourceType==='public')s+=.06;if(f.risk==='high'||t.risk==='high')s-=.17;if(['shoes','tops'].includes(category))s+=.04;if(['leather','denim','tailored'].includes(material))s-=.04;return Math.max(.25,Math.min(.92,s))}
export function analyzeSize(input){const from=findBrand(input.fromBrand)||brands[0];const to=findBrand(input.toBrand)||brands[2];const cat=input.category||'tops';const confidence=confidenceV2(input);let recommended=input.size||'M',alternative='eine Größe prüfen';if(cat==='tops'){recommended=input.size||'M';alternative='Fit Preference beachten'}if(cat==='shoes'){recommended=input.shoeSize||'EU 42';alternative='halbe Größe oder Width prüfen'}if(cat==='jeans'){recommended=`${input.waist||'W32'} / ${input.length||'L32'}`;alternative='W31/W33 testen'}if(cat==='luxury'){recommended=input.size||'IT 48';alternative='Tailored Fit prüfen'}if(cat==='kids'){recommended=input.size||'EU 116';alternative='CM Körpergröße bevorzugen'}if(cat==='lingerie'){recommended=`${input.band||'EU 75'} ${input.cup||'C'}`;alternative='Band + Cup bestätigen'}const risk=(from.risk==='high'||to.risk==='high')?'high':confidence>.78?'low':'medium';const similar=brands.filter(b=>b.id!==to.id&&(b.segment===to.segment||b.region===to.region)).slice(0,4).map(b=>b.name);return {fromBrandName:from.name,toBrandName:to.name,category:cat,recommended,alternative,similar,confidenceScore:confidence,confidencePercent:pct(confidence),marketplaceRisk:risk,sourceType:from.sourceType==='public'&&to.sourceType==='public'?'public + AI-ready':'estimated + AI-ready',fitExplanation:`${to.name}: ${to.fit}. ${cat==='shoes'?'Breite und Region sind bei Schuhen entscheidend.':''}`,materialImpact:['leather','denim','tailored'].includes(input.material)?'Material kann enger wirken.':'Materialrisiko normal.',why:['Brand Fit DNA','Kategorie-Logik','Marketplace Risk','Material/Fit Präferenz','AI-ready Confidence Engine']}}
export function parseFashionQuestion(q){const t=String(q||'').toLowerCase();const category=t.includes('schuh')||t.includes('sneaker')||t.includes('hoka')?'shoes':t.includes('jeans')?'jeans':t.includes('lingerie')?'lingerie':'tops';const brandsFound=brands.filter(b=>t.includes(b.id)||t.includes(b.name.toLowerCase())||(b.aliases||[]).some(a=>t.includes(a.toLowerCase()))).map(b=>b.name);return {category,brandsFound,intent:t.includes('risiko')?'risk':t.includes('größer')||t.includes('kleiner')?'fit_compare':'size_answer'}}
