import brands from '../data/brands.json';
import sizeMappings from '../data/sizeMappings.json';
export {brands,sizeMappings};
export function normalizeBrand(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
export function findBrand(q){const n=normalizeBrand(q);return brands.find(b=>b.id===n||normalizeBrand(b.name)===n||(b.aliases||[]).some(a=>normalizeBrand(a)===n))||null}
export function searchBrands(q){const n=normalizeBrand(q);if(!n)return brands;return brands.filter(b=>b.id.includes(n)||normalizeBrand(b.name).includes(n)||(b.aliases||[]).some(a=>normalizeBrand(a).includes(n)))}
export function percent(v){return `${Math.round((v||0)*100)}%`}
export function convertSize({fromBrand,toBrand,inputSize='M'}){const f=findBrand(fromBrand)||brands[0];const t=findBrand(toBrand)||brands[2];const s=String(inputSize).toUpperCase();const m=sizeMappings.find(x=>x.fromBrand===f.id&&x.toBrand===t.id&&x.inputSize===s);if(m)return{...m,fromBrandName:f.name,toBrandName:t.name,confidencePercent:percent(m.confidenceScore),why:`${t.name}: ${t.fit}`,note:`${f.name} ${s} entspricht bei ${t.name} ungefähr ${m.outputSize}.`};return{fromBrandName:f.name,toBrandName:t.name,inputSize:s,outputSize:s,confidenceScore:.42,confidencePercent:'42%',sourceType:'estimated',returnRisk:'high',fitType:t.fit,why:'Grobe Orientierung',note:'Für diese Kombination liegt noch keine Detailrelation vor.'}}
export function inspectOutfitLinks(links){return links.map((url,i)=>({url:String(url||'').trim(),index:i+1})).filter(x=>x.url).map(item=>{let domain='unbekannt',secure=false;try{const u=new URL(item.url);domain=u.hostname.replace('www.','');secure=u.protocol==='https:'}catch(e){}const lower=item.url.toLowerCase();const brand=brands.find(b=>lower.includes(b.id)||(b.aliases||[]).some(a=>lower.includes(a.replaceAll(' ',''))))||null;const role=lower.includes('shoe')||lower.includes('schuh')||lower.includes('sneaker')?'Schuhe':lower.includes('shirt')||lower.includes('top')?'Shirt/Top':lower.includes('hose')||lower.includes('pants')||lower.includes('jeans')?'Hose':lower.includes('jacket')||lower.includes('jacke')?'Jacke':'Produkt';return{...item,domain,secure,role,brandName:brand?.name||'vom Nutzer bestätigen',confidence:brand?'mittel':'niedrig',risk:secure?'prüfbar':'unsicher'}})}
